In [1]:
import torch
import torch.nn.functional as F
from torch import nn

# 减去均值的自定义层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
# 将自定义层集成到更复杂的网络中
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.4634e-09, grad_fn=<MeanBackward0>)

In [5]:
# 带有参数的层
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.0097,  0.0474,  0.4313],
        [ 0.4998,  0.5164,  0.8943],
        [ 0.7370, -0.9701,  1.1482],
        [ 0.3822,  1.4086, -0.4106],
        [-1.0445, -0.4366,  0.0912]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.7077, 0.8736],
        [0.0000, 1.1367, 0.9685]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[4.7256],
        [6.4410]])